type User {
  email: String! @unique
  netlifyId: String! @unique
  links: [Link!]! @relation
  lists: [List!]! @relation
}

type Link {
  name: String
  url: String!
  author: User!
  isRead: Boolean!
  list: List
}

type List {
  name: String!
  description: String
  isPrivate: Boolean!
  links: [Link!]! @relation
  author: User!
}

type Query {
  allUsers: [User!]!
  allLinks: [Link!]!
  allLists: [List!]!
}
