type User {
  email: String! @unique
  netlifyId: String! @unique
}

type Link {
  name: String
  url: String!
  author: User!
  isRead: Boolean!
  list: List
  createdAt: Time!
}

type List {
  name: String!
  description: String
  isPrivate: Boolean!
  author: User!
  createdAt: Time!
}

type Query {
  allUsers: [User!]!
  allLinks: [Link!]!
  allLists: [List!]!
}
